PR #47844: Fix std error when building the magic-wand demo for zephyr_vexriscv
Imported from GitHub PR https://github.com/tensorflow/tensorflow/pull/47844

When compiling the magic-wand demo for the zephyr_vexriscv target (with command: `make -f tensorflow/lite/micro/tools/make/Makefile TARGET=zephyr_vexriscv magic_wand_bin`) there are the following errors:

```
tensorflow/lite/kernels/internal/reference/elu.h:31:40: error: 'expm1' is not a member of 'std'; did you mean 'exp'?
tensorflow/lite/micro/kernels/elu.cc:57:33: error: 'round' is not a member of 'std'; did you mean 'round'?
```
This happens on a current master branch.

It looks like declaring std global switch for `expm1` function and changing `std::round` to `TfLiteRound` in `elu.cc` solves the problem.

Related to https://github.com/tensorflow/tensorflow/issues/47622#issuecomment-794696077
Copybara import of the project:

--
d804a2df54be88bd73a55eb1ce8de59a17400bbf by Dawid Wojciechowski <dwojciechowski@antmicro.com>:

Declare STD global switch for expm1

--
9dcf7c2f5bc96e278d404b6d1373b6e28236d32b by Dawid Wojciechowski <dwojciechowski@antmicro.com>:

Use TfLiteRound instead of std::round

COPYBARA_INTEGRATE_REVIEW=https://github.com/tensorflow/tensorflow/pull/47844 from antmicro:fix-std-error 9dcf7c2f5bc96e278d404b6d1373b6e28236d32b
PiperOrigin-RevId: 363286780
Change-Id: I1b033d7a51adc89231bb2a763ede20beb97f7169