Fix the Xtensa Vision P6 build.
https://github.com/tensorflow/tensorflow/pull/47199 broke the Vision P6
build with the following error message:
```
tensorflow/lite/micro/kernels/xtensa/quantize.cc:144:5: error: static_assert failed "Unsupported xtensa architecture."
    static_assert(false, "Unsupported xtensa architecture.");
```

Manually confirmed that with this change, the following command passes:
```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=xtensa OPTIMIZED_KERNEL_DIR=xtensa TARGET_ARCH=vision_p6 XTENSA_CORE=P6_200528 test -j8
```