TFLite: iOS: Ensure we use the iOS mktemp
It's fairly common for iOS developers to have mktemp from coreutils
installed and sitting in front of the iOS mktemp on their PATH. Since the
coreutils version has different flags, trying to build tflite from source
results in the following error:

    ERROR: /Users/mgalgs/development/tensorflow/tensorflow/lite/ios/BUILD:49:28: Executing genrule //tensorflow/lite/ios:TensorFlowLiteC_framework failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
    mktemp: too few X's in template 'framework'
    Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build

Fix this by using the mktemp from /usr/bin/ explicitly.